apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-php-config
  namespace: default
data:
  wordpress-custom.ini: |-
    file_uploads = On
    memory_limit = 256M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 300
    max_input_time = 1000  
  another-one.ini: |-
    some_other_php_stuff = true